### ISSUE TITLE
Population statictic for towns

### ISSUE THREAD

**Issue by alexeyknyshev** [alexeyknyshev/android_cash_points#38]
There is significant difference in potential votes count between [Tolstopalzevo](https://ru.wikipedia.org/wiki/%D0%A2%D0%BE%D0%BB%D1%81%D1%82%D0%BE%D0%BF%D0%B0%D0%BB%D1%8C%D1%86%D0%B5%D0%B2%D0%BE_%28%D0%BF%D0%BE%D1%81%D1%91%D0%BB%D0%BE%D0%BA%29) and Moscow due to huge difference in population.

We need in some sort of metric for towns which will be seed for [PATCH_APPROVE_VOTES](https://github.com/alexeyknyshev/android_cash_points/blob/master/server/tnt_workdir/api/cpapi.lua#L430) limit

**Comment by CloudedCat** [comment]
I'd like to use population statistics from http://www.gks.ru/wps/wcm/connect/rosstat_main/rosstat/ru/statistics/publications/catalog/afc8ea004d56a39ab251f2bafc3a6fce for January 1, 2015

**Comment by alexeyknyshev** [comment]
Implemented by @CloudedCat in https://github.com/alexeyknyshev/android_cash_points/pull/43
